name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  verify-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          CI: false

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
